"""initial_schema

Revision ID: 39038320b4c5
Revises:
Create Date: 2026-03-19 19:26:52.746271

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39038320b4c5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_rag_chunks_embedding_hnsw"),
        table_name="rag_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_table("rag_chunks")
    op.drop_index(
        op.f("ix_password_reset_tokens_expiry_used"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_user_created"),
        table_name="password_reset_tokens",
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(
        op.f("ix_email_verification_tokens_expiry_used"),
        table_name="email_verification_tokens",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_user_created"),
        table_name="email_verification_tokens",
    )
    op.drop_table("email_verification_tokens")
    op.alter_column(
        "messages",
        "is_generating",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "messages",
        "is_generating",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("token_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("email_verification_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_verification_tokens_pkey")),
        sa.UniqueConstraint(
            "token_hash",
            name=op.f("email_verification_tokens_token_hash_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_email_verification_tokens_user_created"),
        "email_verification_tokens",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_verification_tokens_expiry_used"),
        "email_verification_tokens",
        ["expires_at", "used_at"],
        unique=False,
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("token_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("password_reset_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("password_reset_tokens_pkey")),
        sa.UniqueConstraint(
            "token_hash",
            name=op.f("password_reset_tokens_token_hash_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_created"),
        "password_reset_tokens",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_expiry_used"),
        "password_reset_tokens",
        ["expires_at", "used_at"],
        unique=False,
    )
    op.create_table(
        "rag_chunks",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("doc_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("doc_version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("chunk_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("chunk_index", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("rag_chunks_pkey")),
        sa.UniqueConstraint(
            "doc_id",
            "doc_version",
            "chunk_id",
            name=op.f("rag_chunks_unique"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_rag_chunks_embedding_hnsw"),
        "rag_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
